dist: trusty

language: android
android:
  components:
    - build-tools-21.1.2
    - android-21

addons:
  apt:
    packages:
    - build-essential
    - python2.7-dev

env:
  global:
    - ANDROID_NDK_VERSION=r10e
    - ANDROID_HOME=/usr/local/android-sdk
    - ANDROID_SDK_ROOT=$ANDROID_HOME/sdk
    - ANDROID_NDK_ROOT=$ANDROID_HOME/android-ndk-${ANDROID_NDK_VERSION}
    - OPENSSL_VERSION=1.0.2o
    - CRYPTOGRAPHY_VERSION=2.2.2

install:
  - wget "https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip"
  - unzip -qq "android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip" -d "${ANDROID_HOME}"

script:
  - ./build-openssl.sh
